/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { FailResponse } from '../models';
/**
 * DocumentsApi - axios parameter creator
 * @export
 */
export const DocumentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Download the original document file. Returns the file as a streaming response with appropriate Content-Type and Content-Disposition headers. The file is streamed through the backend to support internal network deployments and maintain access control.  **Document Lifecycle and Download Availability:** - UPLOADED: Downloadable (temporary status, auto-deleted after 24 hours if not confirmed) - PENDING/RUNNING/COMPLETE/FAILED: Downloadable (permanent, not auto-deleted) - EXPIRED: Not downloadable (file deleted by cleanup task) - DELETED: Not downloadable (soft-deleted by user)  **Auto-Cleanup Mechanism:** A scheduled task runs every 10 minutes to clean up documents in UPLOADED status that are older than 24 hours. Once confirmed, documents will never be auto-deleted. 
         * @summary Download document file
         * @param {string} collectionId Collection ID
         * @param {string} documentId Document ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadDocument: async (collectionId: string, documentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'collectionId' is not null or undefined
            assertParamExists('downloadDocument', 'collectionId', collectionId)
            // verify required parameter 'documentId' is not null or undefined
            assertParamExists('downloadDocument', 'documentId', documentId)
            const localVarPath = `/collections/{collection_id}/documents/{document_id}/download`
                .replace(`{${"collection_id"}}`, encodeURIComponent(String(collectionId)))
                .replace(`{${"document_id"}}`, encodeURIComponent(String(documentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DocumentsApi - functional programming interface
 * @export
 */
export const DocumentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DocumentsApiAxiosParamCreator(configuration)
    return {
        /**
         * Download the original document file. Returns the file as a streaming response with appropriate Content-Type and Content-Disposition headers. The file is streamed through the backend to support internal network deployments and maintain access control.  **Document Lifecycle and Download Availability:** - UPLOADED: Downloadable (temporary status, auto-deleted after 24 hours if not confirmed) - PENDING/RUNNING/COMPLETE/FAILED: Downloadable (permanent, not auto-deleted) - EXPIRED: Not downloadable (file deleted by cleanup task) - DELETED: Not downloadable (soft-deleted by user)  **Auto-Cleanup Mechanism:** A scheduled task runs every 10 minutes to clean up documents in UPLOADED status that are older than 24 hours. Once confirmed, documents will never be auto-deleted. 
         * @summary Download document file
         * @param {string} collectionId Collection ID
         * @param {string} documentId Document ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async downloadDocument(collectionId: string, documentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.downloadDocument(collectionId, documentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DocumentsApi.downloadDocument']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DocumentsApi - factory interface
 * @export
 */
export const DocumentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DocumentsApiFp(configuration)
    return {
        /**
         * Download the original document file. Returns the file as a streaming response with appropriate Content-Type and Content-Disposition headers. The file is streamed through the backend to support internal network deployments and maintain access control.  **Document Lifecycle and Download Availability:** - UPLOADED: Downloadable (temporary status, auto-deleted after 24 hours if not confirmed) - PENDING/RUNNING/COMPLETE/FAILED: Downloadable (permanent, not auto-deleted) - EXPIRED: Not downloadable (file deleted by cleanup task) - DELETED: Not downloadable (soft-deleted by user)  **Auto-Cleanup Mechanism:** A scheduled task runs every 10 minutes to clean up documents in UPLOADED status that are older than 24 hours. Once confirmed, documents will never be auto-deleted. 
         * @summary Download document file
         * @param {DocumentsApiDownloadDocumentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadDocument(requestParameters: DocumentsApiDownloadDocumentRequest, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.downloadDocument(requestParameters.collectionId, requestParameters.documentId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DocumentsApi - interface
 * @export
 * @interface DocumentsApi
 */
export interface DocumentsApiInterface {
    /**
     * Download the original document file. Returns the file as a streaming response with appropriate Content-Type and Content-Disposition headers. The file is streamed through the backend to support internal network deployments and maintain access control.  **Document Lifecycle and Download Availability:** - UPLOADED: Downloadable (temporary status, auto-deleted after 24 hours if not confirmed) - PENDING/RUNNING/COMPLETE/FAILED: Downloadable (permanent, not auto-deleted) - EXPIRED: Not downloadable (file deleted by cleanup task) - DELETED: Not downloadable (soft-deleted by user)  **Auto-Cleanup Mechanism:** A scheduled task runs every 10 minutes to clean up documents in UPLOADED status that are older than 24 hours. Once confirmed, documents will never be auto-deleted. 
     * @summary Download document file
     * @param {DocumentsApiDownloadDocumentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApiInterface
     */
    downloadDocument(requestParameters: DocumentsApiDownloadDocumentRequest, options?: RawAxiosRequestConfig): AxiosPromise<File>;

}

/**
 * Request parameters for downloadDocument operation in DocumentsApi.
 * @export
 * @interface DocumentsApiDownloadDocumentRequest
 */
export interface DocumentsApiDownloadDocumentRequest {
    /**
     * Collection ID
     * @type {string}
     * @memberof DocumentsApiDownloadDocument
     */
    readonly collectionId: string

    /**
     * Document ID
     * @type {string}
     * @memberof DocumentsApiDownloadDocument
     */
    readonly documentId: string
}

/**
 * DocumentsApi - object-oriented interface
 * @export
 * @class DocumentsApi
 * @extends {BaseAPI}
 */
export class DocumentsApi extends BaseAPI implements DocumentsApiInterface {
    /**
     * Download the original document file. Returns the file as a streaming response with appropriate Content-Type and Content-Disposition headers. The file is streamed through the backend to support internal network deployments and maintain access control.  **Document Lifecycle and Download Availability:** - UPLOADED: Downloadable (temporary status, auto-deleted after 24 hours if not confirmed) - PENDING/RUNNING/COMPLETE/FAILED: Downloadable (permanent, not auto-deleted) - EXPIRED: Not downloadable (file deleted by cleanup task) - DELETED: Not downloadable (soft-deleted by user)  **Auto-Cleanup Mechanism:** A scheduled task runs every 10 minutes to clean up documents in UPLOADED status that are older than 24 hours. Once confirmed, documents will never be auto-deleted. 
     * @summary Download document file
     * @param {DocumentsApiDownloadDocumentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApi
     */
    public downloadDocument(requestParameters: DocumentsApiDownloadDocumentRequest, options?: RawAxiosRequestConfig) {
        return DocumentsApiFp(this.configuration).downloadDocument(requestParameters.collectionId, requestParameters.documentId, options).then((request) => request(this.axios, this.basePath));
    }
}

