apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atrag-ingress
  labels:
    {{- include "atrag.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: atrag
            port:
              number: 8000
      - pathType: Prefix
        path: "/mcp"
        backend:
          service:
            name: atrag
            port:
              number: 8000
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: atrag-frontend
            port:
              number: 3000
    {{- if .Values.api.domainName }}
    host: {{ .Values.api.domainName }}
    {{- end }}