/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Collection } from './collection';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelSpec } from './model-spec';

/**
 * Message format for agent-type bots with additional capabilities
 * @export
 * @interface AgentMessage
 */
export interface AgentMessage {
    /**
     * User query
     * @type {string}
     * @memberof AgentMessage
     */
    'query': string;
    /**
     * List of collection objects to search in
     * @type {Array<Collection>}
     * @memberof AgentMessage
     */
    'collections': Array<Collection>;
    /**
     * Model specification for completion including provider and model details
     * @type {ModelSpec}
     * @memberof AgentMessage
     */
    'completion'?: ModelSpec;
    /**
     * Optional LLM used by the hybrid pre-router. The server resolves its API
     * key from the current user's provider configuration.
     * @type {ModelSpec}
     * @memberof AgentMessage
     */
    'routing_completion'?: ModelSpec;
    /**
     * Whether to enable web search
     * @type {boolean}
     * @memberof AgentMessage
     */
    'web_search_enabled'?: boolean;
    /**
     * Language preference for the response
     * @type {string}
     * @memberof AgentMessage
     */
    'language'?: AgentMessageLanguageEnum;
    /**
     * 
     * @type {Array<any>}
     * @memberof AgentMessage
     */
    'files'?: Array<any>;
}

export const AgentMessageLanguageEnum = {
    en_US: 'en-US',
    zh_CN: 'zh-CN',
    zh_TW: 'zh-TW',
    ja_JP: 'ja-JP',
    ko_KR: 'ko-KR',
    fr_FR: 'fr-FR',
    de_DE: 'de-DE',
    es_ES: 'es-ES',
    it_IT: 'it-IT',
    pt_BR: 'pt-BR',
    ru_RU: 'ru-RU'
} as const;

export type AgentMessageLanguageEnum = typeof AgentMessageLanguageEnum[keyof typeof AgentMessageLanguageEnum];


