/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AgentErrorResponse
 */
export interface AgentErrorResponse {
    /**
     * The type of the response, must be \'error\'.
     * @type {string}
     * @memberof AgentErrorResponse
     */
    'type'?: AgentErrorResponseTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AgentErrorResponse
     */
    'id'?: string;
    /**
     * Error message
     * @type {string}
     * @memberof AgentErrorResponse
     */
    'data'?: string;
    /**
     * 
     * @type {number}
     * @memberof AgentErrorResponse
     */
    'timestamp'?: number;
}

export const AgentErrorResponseTypeEnum = {
    error: 'error'
} as const;

export type AgentErrorResponseTypeEnum = typeof AgentErrorResponseTypeEnum[keyof typeof AgentErrorResponseTypeEnum];


