/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiKey } from './api-key';
// May contain unused imports in some cases
// @ts-ignore
import type { PageResult } from './page-result';

/**
 * A list of API keys
 * @export
 * @interface ApiKeyList
 */
export interface ApiKeyList {
    /**
     * 
     * @type {Array<ApiKey>}
     * @memberof ApiKeyList
     */
    'items'?: Array<ApiKey>;
    /**
     * 
     * @type {PageResult}
     * @memberof ApiKeyList
     */
    'pageResult'?: PageResult;
}

