/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Audit log entry
 * @export
 * @interface AuditLog
 */
export interface AuditLog {
    /**
     * Audit log ID
     * @type {string}
     * @memberof AuditLog
     */
    'id'?: string;
    /**
     * User ID who performed the action
     * @type {string}
     * @memberof AuditLog
     */
    'user_id'?: string;
    /**
     * Username for display
     * @type {string}
     * @memberof AuditLog
     */
    'username'?: string;
    /**
     * Type of resource
     * @type {string}
     * @memberof AuditLog
     */
    'resource_type'?: AuditLogResourceTypeEnum;
    /**
     * ID of the resource (extracted at query time)
     * @type {string}
     * @memberof AuditLog
     */
    'resource_id'?: string;
    /**
     * API operation name
     * @type {string}
     * @memberof AuditLog
     */
    'api_name'?: string;
    /**
     * HTTP method (POST, PUT, DELETE)
     * @type {string}
     * @memberof AuditLog
     */
    'http_method'?: string;
    /**
     * API path
     * @type {string}
     * @memberof AuditLog
     */
    'path'?: string;
    /**
     * HTTP status code
     * @type {number}
     * @memberof AuditLog
     */
    'status_code'?: number;
    /**
     * Request start time (milliseconds since epoch)
     * @type {number}
     * @memberof AuditLog
     */
    'start_time'?: number;
    /**
     * Request end time (milliseconds since epoch)
     * @type {number}
     * @memberof AuditLog
     */
    'end_time'?: number;
    /**
     * Request duration in milliseconds (calculated)
     * @type {number}
     * @memberof AuditLog
     */
    'duration_ms'?: number;
    /**
     * Request data (JSON string)
     * @type {string}
     * @memberof AuditLog
     */
    'request_data'?: string;
    /**
     * Response data (JSON string)
     * @type {string}
     * @memberof AuditLog
     */
    'response_data'?: string;
    /**
     * Error message if failed
     * @type {string}
     * @memberof AuditLog
     */
    'error_message'?: string;
    /**
     * Client IP address
     * @type {string}
     * @memberof AuditLog
     */
    'ip_address'?: string;
    /**
     * User agent string
     * @type {string}
     * @memberof AuditLog
     */
    'user_agent'?: string;
    /**
     * Request ID for tracking
     * @type {string}
     * @memberof AuditLog
     */
    'request_id'?: string;
    /**
     * Created timestamp
     * @type {string}
     * @memberof AuditLog
     */
    'created'?: string;
}

export const AuditLogResourceTypeEnum = {
    collection: 'collection',
    document: 'document',
    bot: 'bot',
    chat: 'chat',
    message: 'message',
    api_key: 'api_key',
    llm: 'llm',
    llm_provider: 'llm_provider',
    llm_provider_model: 'llm_provider_model',
    model_service_provider: 'model_service_provider',
    user: 'user',
    flow: 'flow',
    search: 'search',
    index: 'index'
} as const;

export type AuditLogResourceTypeEnum = typeof AuditLogResourceTypeEnum[keyof typeof AuditLogResourceTypeEnum];


