/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuditLog } from './audit-log';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginatedResponse } from './paginated-response';

/**
 * @type AuditLogList
 * List of audit logs with pagination
 * @export
 */
export type AuditLogList = PaginatedResponse;


