/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BotConfig } from './bot-config';

/**
 * 
 * @export
 * @interface BotCreate
 */
export interface BotCreate {
    /**
     * 
     * @type {string}
     * @memberof BotCreate
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof BotCreate
     */
    'description'?: string;
    /**
     * The type of bot
     * @type {string}
     * @memberof BotCreate
     */
    'type'?: BotCreateTypeEnum;
    /**
     * 
     * @type {BotConfig}
     * @memberof BotCreate
     */
    'config'?: BotConfig;
}

export const BotCreateTypeEnum = {
    knowledge: 'knowledge',
    common: 'common',
    agent: 'agent'
} as const;

export type BotCreateTypeEnum = typeof BotCreateTypeEnum[keyof typeof BotCreateTypeEnum];


