/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BotConfigAgent } from './bot-config-agent';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowDefinition } from './workflow-definition';

/**
 * 
 * @export
 * @interface BotConfig
 */
export interface BotConfig {
    /**
     * 
     * @type {BotConfigAgent}
     * @memberof BotConfig
     */
    'agent'?: BotConfigAgent;
    /**
     * 
     * @type {WorkflowDefinition}
     * @memberof BotConfig
     */
    'flow'?: WorkflowDefinition;
}

