/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BotConfig } from './bot-config';

/**
 * 
 * @export
 * @interface BotUpdate
 */
export interface BotUpdate {
    /**
     * 
     * @type {string}
     * @memberof BotUpdate
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof BotUpdate
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof BotUpdate
     */
    'description'?: string;
    /**
     * 
     * @type {BotConfig}
     * @memberof BotUpdate
     */
    'config'?: BotConfig;
}

