/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChangePassword
 */
export interface ChangePassword {
    /**
     * The username of the user
     * @type {string}
     * @memberof ChangePassword
     */
    'username'?: string;
    /**
     * The old password of the user
     * @type {string}
     * @memberof ChangePassword
     */
    'old_password'?: string;
    /**
     * The new password of the user
     * @type {string}
     * @memberof ChangePassword
     */
    'new_password'?: string;
}

