/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CollectionSourceFeishu
 */
export interface CollectionSourceFeishu {
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceFeishu
     */
    'app_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceFeishu
     */
    'app_secret'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceFeishu
     */
    'space_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceFeishu
     */
    'node_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceFeishu
     */
    'method'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceFeishu
     */
    'target_format'?: string;
}

