/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CollectionSourceEmail } from './collection-source-email';
// May contain unused imports in some cases
// @ts-ignore
import type { CollectionSourceFeishu } from './collection-source-feishu';
// May contain unused imports in some cases
// @ts-ignore
import type { CollectionSourceFtp } from './collection-source-ftp';
// May contain unused imports in some cases
// @ts-ignore
import type { CollectionSourceLocal } from './collection-source-local';
// May contain unused imports in some cases
// @ts-ignore
import type { CollectionSourceOss } from './collection-source-oss';
// May contain unused imports in some cases
// @ts-ignore
import type { CollectionSourceS3 } from './collection-source-s3';
// May contain unused imports in some cases
// @ts-ignore
import type { CollectionSourceUrl } from './collection-source-url';

/**
 * 
 * @export
 * @interface CollectionSource
 */
export interface CollectionSource {
    /**
     * 
     * @type {string}
     * @memberof CollectionSource
     */
    'category'?: CollectionSourceCategoryEnum;
    /**
     * 
     * @type {object}
     * @memberof CollectionSource
     */
    'upload'?: object;
    /**
     * 
     * @type {CollectionSourceLocal}
     * @memberof CollectionSource
     */
    'local'?: CollectionSourceLocal;
    /**
     * 
     * @type {CollectionSourceOss}
     * @memberof CollectionSource
     */
    'oss'?: CollectionSourceOss;
    /**
     * 
     * @type {CollectionSourceS3}
     * @memberof CollectionSource
     */
    's3'?: CollectionSourceS3;
    /**
     * 
     * @type {CollectionSourceFtp}
     * @memberof CollectionSource
     */
    'ftp'?: CollectionSourceFtp;
    /**
     * 
     * @type {CollectionSourceEmail}
     * @memberof CollectionSource
     */
    'email'?: CollectionSourceEmail;
    /**
     * 
     * @type {CollectionSourceUrl}
     * @memberof CollectionSource
     */
    'url'?: CollectionSourceUrl;
    /**
     * 
     * @type {CollectionSourceFeishu}
     * @memberof CollectionSource
     */
    'feishu'?: CollectionSourceFeishu;
}

export const CollectionSourceCategoryEnum = {
    upload: 'upload',
    tencent: 'tencent',
    oss: 'oss',
    local: 'local',
    s3: 's3',
    ftp: 'ftp',
    email: 'email',
    url: 'url',
    github: 'github'
} as const;

export type CollectionSourceCategoryEnum = typeof CollectionSourceCategoryEnum[keyof typeof CollectionSourceCategoryEnum];


