/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IndexPrompts } from './index-prompts';
// May contain unused imports in some cases
// @ts-ignore
import type { KnowledgeGraphConfig } from './knowledge-graph-config';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelSpec } from './model-spec';

/**
 * 
 * @export
 * @interface CollectionConfig
 */
export interface CollectionConfig {
    /**
     * Source system identifier
     * @type {string}
     * @memberof CollectionConfig
     */
    'source'?: string;
    /**
     * Whether to enable vector index
     * @type {boolean}
     * @memberof CollectionConfig
     */
    'enable_vector'?: boolean;
    /**
     * Whether to enable fulltext index
     * @type {boolean}
     * @memberof CollectionConfig
     */
    'enable_fulltext'?: boolean;
    /**
     * Whether to enable knowledge graph index
     * @type {boolean}
     * @memberof CollectionConfig
     */
    'enable_knowledge_graph'?: boolean;
    /**
     * Whether to enable summary index
     * @type {boolean}
     * @memberof CollectionConfig
     */
    'enable_summary'?: boolean;
    /**
     * Whether to enable vision index
     * @type {boolean}
     * @memberof CollectionConfig
     */
    'enable_vision'?: boolean;
    /**
     * 
     * @type {KnowledgeGraphConfig}
     * @memberof CollectionConfig
     */
    'knowledge_graph_config'?: KnowledgeGraphConfig;
    /**
     * 
     * @type {IndexPrompts}
     * @memberof CollectionConfig
     */
    'index_prompts'?: IndexPrompts;
    /**
     * Language for the collection content and processing
     * @type {string}
     * @memberof CollectionConfig
     */
    'language'?: CollectionConfigLanguageEnum;
    /**
     * 
     * @type {ModelSpec}
     * @memberof CollectionConfig
     */
    'embedding'?: ModelSpec;
    /**
     * 
     * @type {ModelSpec}
     * @memberof CollectionConfig
     */
    'completion'?: ModelSpec;
    /**
     * Path for local and ftp sources
     * @type {string}
     * @memberof CollectionConfig
     * @deprecated
     */
    'path'?: string;
    /**
     * FTP host
     * @type {string}
     * @memberof CollectionConfig
     * @deprecated
     */
    'host'?: string;
    /**
     * FTP username
     * @type {string}
     * @memberof CollectionConfig
     * @deprecated
     */
    'username'?: string;
    /**
     * FTP password
     * @type {string}
     * @memberof CollectionConfig
     * @deprecated
     */
    'password'?: string;
    /**
     * Region for S3/OSS
     * @type {string}
     * @memberof CollectionConfig
     * @deprecated
     */
    'region'?: string;
    /**
     * Access key ID for S3/OSS
     * @type {string}
     * @memberof CollectionConfig
     * @deprecated
     */
    'access_key_id'?: string;
    /**
     * Secret access key for S3/OSS
     * @type {string}
     * @memberof CollectionConfig
     * @deprecated
     */
    'secret_access_key'?: string;
    /**
     * Bucket name for S3/OSS
     * @type {string}
     * @memberof CollectionConfig
     * @deprecated
     */
    'bucket'?: string;
    /**
     * Directory path in bucket for S3/OSS
     * @type {string}
     * @memberof CollectionConfig
     * @deprecated
     */
    'dir'?: string;
    /**
     * Email source configuration
     * @type {object}
     * @memberof CollectionConfig
     * @deprecated
     */
    'email_source'?: object;
    /**
     * POP3 server address
     * @type {string}
     * @memberof CollectionConfig
     * @deprecated
     */
    'pop_server'?: string;
    /**
     * Email server port
     * @type {string}
     * @memberof CollectionConfig
     * @deprecated
     */
    'port'?: string;
    /**
     * Email address
     * @type {string}
     * @memberof CollectionConfig
     * @deprecated
     */
    'email_address'?: string;
    /**
     * Email password
     * @type {string}
     * @memberof CollectionConfig
     * @deprecated
     */
    'email_password'?: string;
    /**
     * Feishu app ID
     * @type {string}
     * @memberof CollectionConfig
     * @deprecated
     */
    'app_id'?: string;
    /**
     * Feishu app secret
     * @type {string}
     * @memberof CollectionConfig
     * @deprecated
     */
    'app_secret'?: string;
    /**
     * Feishu space ID
     * @type {string}
     * @memberof CollectionConfig
     * @deprecated
     */
    'space_id'?: string;
}

export const CollectionConfigLanguageEnum = {
    zh_CN: 'zh-CN',
    en_US: 'en-US',
    ja_JP: 'ja-JP',
    ko_KR: 'ko-KR'
} as const;

export type CollectionConfigLanguageEnum = typeof CollectionConfigLanguageEnum[keyof typeof CollectionConfigLanguageEnum];


