/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CollectionView } from './collection-view';
// May contain unused imports in some cases
// @ts-ignore
import type { PageResult } from './page-result';

/**
 * A list of collection views
 * @export
 * @interface CollectionViewList
 */
export interface CollectionViewList {
    /**
     * 
     * @type {Array<CollectionView>}
     * @memberof CollectionViewList
     */
    'items'?: Array<CollectionView>;
    /**
     * 
     * @type {PageResult}
     * @memberof CollectionViewList
     */
    'pageResult'?: PageResult;
}

