/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CollectionsCollectionIdSummaryGeneratePost200Response
 */
export interface CollectionsCollectionIdSummaryGeneratePost200Response {
    /**
     * 
     * @type {string}
     * @memberof CollectionsCollectionIdSummaryGeneratePost200Response
     */
    'collection_id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionsCollectionIdSummaryGeneratePost200Response
     */
    'success'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CollectionsCollectionIdSummaryGeneratePost200Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionsCollectionIdSummaryGeneratePost200Response
     */
    'status'?: string;
}

