/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Lightweight collection information for lists, MCP and agents
 * @export
 * @interface CollectionView
 */
export interface CollectionView {
    /**
     * 
     * @type {string}
     * @memberof CollectionView
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionView
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionView
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionView
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionView
     */
    'status'?: CollectionViewStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CollectionView
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionView
     */
    'updated'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionView
     */
    'is_published'?: boolean;
    /**
     * Publication time, null when not published
     * @type {string}
     * @memberof CollectionView
     */
    'published_at'?: string;
    /**
     * Collection owner user ID
     * @type {string}
     * @memberof CollectionView
     */
    'owner_user_id'?: string;
    /**
     * Collection owner username
     * @type {string}
     * @memberof CollectionView
     */
    'owner_username'?: string;
    /**
     * Subscription ID if this is a subscribed collection, null for owned collections
     * @type {string}
     * @memberof CollectionView
     */
    'subscription_id'?: string;
    /**
     * Subscription time, null for owned collections
     * @type {string}
     * @memberof CollectionView
     */
    'subscribed_at'?: string;
}

export const CollectionViewStatusEnum = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    DELETED: 'DELETED'
} as const;

export type CollectionViewStatusEnum = typeof CollectionViewStatusEnum[keyof typeof CollectionViewStatusEnum];


