/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CollectionsCollectionIdRebuildFailedIndexesPost200Response
 */
export interface CollectionsCollectionIdRebuildFailedIndexesPost200Response {
    /**
     * 
     * @type {string}
     * @memberof CollectionsCollectionIdRebuildFailedIndexesPost200Response
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof CollectionsCollectionIdRebuildFailedIndexesPost200Response
     */
    'message': string;
    /**
     * Number of documents with failed indexes that will be rebuilt
     * @type {number}
     * @memberof CollectionsCollectionIdRebuildFailedIndexesPost200Response
     */
    'affected_documents': number;
}

