/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CollectionSourceFtp
 */
export interface CollectionSourceFtp {
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceFtp
     */
    'path'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceFtp
     */
    'host'?: string;
    /**
     * 
     * @type {number}
     * @memberof CollectionSourceFtp
     */
    'port'?: number;
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceFtp
     */
    'username'?: string;
}

