/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CollectionConfig } from './collection-config';
// May contain unused imports in some cases
// @ts-ignore
import type { CollectionSource } from './collection-source';

/**
 * 
 * @export
 * @interface CollectionCreate
 */
export interface CollectionCreate {
    /**
     * 
     * @type {string}
     * @memberof CollectionCreate
     */
    'title'?: string;
    /**
     * 
     * @type {CollectionConfig}
     * @memberof CollectionCreate
     */
    'config'?: CollectionConfig;
    /**
     * 
     * @type {string}
     * @memberof CollectionCreate
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionCreate
     */
    'description'?: string;
    /**
     * 
     * @type {CollectionSource}
     * @memberof CollectionCreate
     */
    'source'?: CollectionSource;
}

