/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CollectionSourceS3
 */
export interface CollectionSourceS3 {
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceS3
     */
    'access_key_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceS3
     */
    'access_key_secret'?: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof CollectionSourceS3
     */
    'buckets'?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceS3
     */
    'bucket'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceS3
     */
    'region'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceS3
     */
    'dir'?: string;
}

