/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CollectionSourceOssBucketsInner } from './collection-source-oss-buckets-inner';

/**
 * 
 * @export
 * @interface CollectionSourceOss
 */
export interface CollectionSourceOss {
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceOss
     */
    'access_key_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceOss
     */
    'access_key_secret'?: string;
    /**
     * 
     * @type {Array<CollectionSourceOssBucketsInner>}
     * @memberof CollectionSourceOss
     */
    'buckets'?: Array<CollectionSourceOssBucketsInner>;
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceOss
     */
    'bucket'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceOss
     */
    'endpoint'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceOss
     */
    'region'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceOss
     */
    'dir'?: string;
}

