/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CollectionSourceEmail
 */
export interface CollectionSourceEmail {
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceEmail
     */
    'pop_server'?: string;
    /**
     * 
     * @type {number}
     * @memberof CollectionSourceEmail
     */
    'port'?: number;
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceEmail
     */
    'email_address'?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionSourceEmail
     */
    'email_password'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionSourceEmail
     */
    'detect_spam'?: boolean;
}

