/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ConfigAuthAuth0 } from './config-auth-auth0';

/**
 * 
 * @export
 * @interface ConfigAuth
 */
export interface ConfigAuth {
    /**
     * 
     * @type {string}
     * @memberof ConfigAuth
     */
    'type'?: ConfigAuthTypeEnum;
    /**
     * 
     * @type {ConfigAuthAuth0}
     * @memberof ConfigAuth
     */
    'auth0'?: ConfigAuthAuth0;
    /**
     * 
     * @type {ConfigAuthAuth0}
     * @memberof ConfigAuth
     */
    'authing'?: ConfigAuthAuth0;
    /**
     * 
     * @type {ConfigAuthAuth0}
     * @memberof ConfigAuth
     */
    'logto'?: ConfigAuthAuth0;
}

export const ConfigAuthTypeEnum = {
    none: 'none',
    auth0: 'auth0',
    authing: 'authing',
    logto: 'logto',
    cookie: 'cookie'
} as const;

export type ConfigAuthTypeEnum = typeof ConfigAuthTypeEnum[keyof typeof ConfigAuthTypeEnum];


