/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ConfirmDocumentsResponseFailedDocumentsInner
 */
export interface ConfirmDocumentsResponseFailedDocumentsInner {
    /**
     * 
     * @type {string}
     * @memberof ConfirmDocumentsResponseFailedDocumentsInner
     */
    'document_id'?: string;
    /**
     * Name of the document
     * @type {string}
     * @memberof ConfirmDocumentsResponseFailedDocumentsInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfirmDocumentsResponseFailedDocumentsInner
     */
    'error'?: string;
}

