/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ConfirmDocumentsRequest
 */
export interface ConfirmDocumentsRequest {
    /**
     * List of document IDs to confirm
     * @type {Array<string>}
     * @memberof ConfirmDocumentsRequest
     */
    'document_ids': Array<string>;
}

