/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ConfirmDocumentsResponseFailedDocumentsInner } from './confirm-documents-response-failed-documents-inner';

/**
 * 
 * @export
 * @interface ConfirmDocumentsResponse
 */
export interface ConfirmDocumentsResponse {
    /**
     * Number of documents successfully confirmed
     * @type {number}
     * @memberof ConfirmDocumentsResponse
     */
    'confirmed_count': number;
    /**
     * Number of documents that failed to confirm
     * @type {number}
     * @memberof ConfirmDocumentsResponse
     */
    'failed_count': number;
    /**
     * Details of failed confirmations
     * @type {Array<ConfirmDocumentsResponseFailedDocumentsInner>}
     * @memberof ConfirmDocumentsResponse
     */
    'failed_documents'?: Array<ConfirmDocumentsResponseFailedDocumentsInner>;
}

