/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeleteUserPromptResponse
 */
export interface DeleteUserPromptResponse {
    /**
     * 
     * @type {string}
     * @memberof DeleteUserPromptResponse
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteUserPromptResponse
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteUserPromptResponse
     */
    'new_content'?: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteUserPromptResponse
     */
    'source'?: DeleteUserPromptResponseSourceEnum;
}

export const DeleteUserPromptResponseSourceEnum = {
    system: 'system',
    hardcoded: 'hardcoded'
} as const;

export type DeleteUserPromptResponseSourceEnum = typeof DeleteUserPromptResponseSourceEnum[keyof typeof DeleteUserPromptResponseSourceEnum];


