/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DocumentCreate
 */
export interface DocumentCreate {
    /**
     * 
     * @type {string}
     * @memberof DocumentCreate
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentCreate
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentCreate
     */
    'source'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentCreate
     */
    'collection_id'?: string;
}

