/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Document } from './document';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginatedResponse } from './paginated-response';

/**
 * @type DocumentList
 * A list of documents with pagination
 * @export
 */
export type DocumentList = PaginatedResponse;


