/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Edge
 */
export interface Edge {
    /**
     * Unique identifier for the edge, only useful for frontend to identify the edge
     * @type {string}
     * @memberof Edge
     */
    'id'?: string;
    /**
     * Whether the edge is deletable, only useful for frontend to delete the edge
     * @type {boolean}
     * @memberof Edge
     */
    'deletable'?: boolean;
    /**
     * Type of the edge
     * @type {string}
     * @memberof Edge
     */
    'type'?: string;
    /**
     * ID of the source node
     * @type {string}
     * @memberof Edge
     */
    'source': string;
    /**
     * ID of the target node
     * @type {string}
     * @memberof Edge
     */
    'target': string;
}

