/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EmbeddingRequestInput } from './embedding-request-input';

/**
 * Request to generate embeddings for text inputs
 * @export
 * @interface EmbeddingRequest
 */
export interface EmbeddingRequest {
    /**
     * LLM provider name (e.g., openai, anthropic)
     * @type {string}
     * @memberof EmbeddingRequest
     */
    'provider': string;
    /**
     * Model name for embedding generation
     * @type {string}
     * @memberof EmbeddingRequest
     */
    'model': string;
    /**
     * 
     * @type {EmbeddingRequestInput}
     * @memberof EmbeddingRequest
     */
    'input': EmbeddingRequestInput;
}

