/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Token usage information for the embedding request
 * @export
 * @interface EmbeddingUsage
 */
export interface EmbeddingUsage {
    /**
     * Number of tokens in the input text(s)
     * @type {number}
     * @memberof EmbeddingUsage
     */
    'prompt_tokens': number;
    /**
     * Total number of tokens used (same as prompt_tokens for embeddings)
     * @type {number}
     * @memberof EmbeddingUsage
     */
    'total_tokens': number;
}

