/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Individual embedding result
 * @export
 * @interface EmbeddingData
 */
export interface EmbeddingData {
    /**
     * Object type identifier
     * @type {string}
     * @memberof EmbeddingData
     */
    'object': string;
    /**
     * The embedding vector as a list of floats
     * @type {Array<number>}
     * @memberof EmbeddingData
     */
    'embedding': Array<number>;
    /**
     * Index of the input text corresponding to this embedding
     * @type {number}
     * @memberof EmbeddingData
     */
    'index': number;
}

