/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EmbeddingData } from './embedding-data';
// May contain unused imports in some cases
// @ts-ignore
import type { EmbeddingUsage } from './embedding-usage';

/**
 * Response containing generated embeddings in OpenAI-compatible format
 * @export
 * @interface EmbeddingResponse
 */
export interface EmbeddingResponse {
    /**
     * Object type identifier
     * @type {string}
     * @memberof EmbeddingResponse
     */
    'object': string;
    /**
     * List of embedding results
     * @type {Array<EmbeddingData>}
     * @memberof EmbeddingResponse
     */
    'data': Array<EmbeddingData>;
    /**
     * Model used for embedding generation
     * @type {string}
     * @memberof EmbeddingResponse
     */
    'model': string;
    /**
     * 
     * @type {EmbeddingUsage}
     * @memberof EmbeddingResponse
     */
    'usage': EmbeddingUsage;
}

