/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExecutionConfigRetry
 */
export interface ExecutionConfigRetry {
    /**
     * Maximum number of retry attempts
     * @type {number}
     * @memberof ExecutionConfigRetry
     */
    'max_attempts'?: number;
    /**
     * Delay between retries in seconds
     * @type {number}
     * @memberof ExecutionConfigRetry
     */
    'delay'?: number;
}

