/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExecutionConfigErrorHandling } from './execution-config-error-handling';
// May contain unused imports in some cases
// @ts-ignore
import type { ExecutionConfigRetry } from './execution-config-retry';

/**
 * Configuration for workflow execution
 * @export
 * @interface ExecutionConfig
 */
export interface ExecutionConfig {
    /**
     * Overall timeout in seconds
     * @type {number}
     * @memberof ExecutionConfig
     */
    'timeout'?: number;
    /**
     * 
     * @type {ExecutionConfigRetry}
     * @memberof ExecutionConfig
     */
    'retry'?: ExecutionConfigRetry;
    /**
     * 
     * @type {ExecutionConfigErrorHandling}
     * @memberof ExecutionConfig
     */
    'error_handling'?: ExecutionConfigErrorHandling;
}

