/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExecutionConfigErrorHandlingNotification } from './execution-config-error-handling-notification';

/**
 * 
 * @export
 * @interface ExecutionConfigErrorHandling
 */
export interface ExecutionConfigErrorHandling {
    /**
     * Error handling strategy
     * @type {string}
     * @memberof ExecutionConfigErrorHandling
     */
    'strategy'?: ExecutionConfigErrorHandlingStrategyEnum;
    /**
     * 
     * @type {ExecutionConfigErrorHandlingNotification}
     * @memberof ExecutionConfigErrorHandling
     */
    'notification'?: ExecutionConfigErrorHandlingNotification;
}

export const ExecutionConfigErrorHandlingStrategyEnum = {
    stop_on_error: 'stop_on_error',
    continue_on_error: 'continue_on_error'
} as const;

export type ExecutionConfigErrorHandlingStrategyEnum = typeof ExecutionConfigErrorHandlingStrategyEnum[keyof typeof ExecutionConfigErrorHandlingStrategyEnum];


