/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExportTaskResponse
 */
export interface ExportTaskResponse {
    /**
     * Unique ID of the export task
     * @type {string}
     * @memberof ExportTaskResponse
     */
    'export_task_id': string;
    /**
     * Current status of the export task
     * @type {string}
     * @memberof ExportTaskResponse
     */
    'status': ExportTaskResponseStatusEnum;
    /**
     * Progress percentage (0-100)
     * @type {number}
     * @memberof ExportTaskResponse
     */
    'progress'?: number;
    /**
     * Human-readable status message
     * @type {string}
     * @memberof ExportTaskResponse
     */
    'message'?: string;
    /**
     * Error detail when status is FAILED
     * @type {string}
     * @memberof ExportTaskResponse
     */
    'error_message'?: string;
    /**
     * URL to download the ZIP file (only set when status is COMPLETED)
     * @type {string}
     * @memberof ExportTaskResponse
     */
    'download_url'?: string;
    /**
     * Size of the ZIP file in bytes
     * @type {number}
     * @memberof ExportTaskResponse
     */
    'file_size'?: number;
    /**
     * 
     * @type {string}
     * @memberof ExportTaskResponse
     */
    'gmt_created'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExportTaskResponse
     */
    'gmt_completed'?: string;
    /**
     * Time when the export file will be automatically deleted (7 days after creation)
     * @type {string}
     * @memberof ExportTaskResponse
     */
    'gmt_expires'?: string;
}

export const ExportTaskResponseStatusEnum = {
    PENDING: 'PENDING',
    PROCESSING: 'PROCESSING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    EXPIRED: 'EXPIRED'
} as const;

export type ExportTaskResponseStatusEnum = typeof ExportTaskResponseStatusEnum[keyof typeof ExportTaskResponseStatusEnum];


