/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FailResponse
 */
export interface FailResponse {
    /**
     * Error code
     * @type {string}
     * @memberof FailResponse
     */
    'code'?: string;
    /**
     * Error message
     * @type {string}
     * @memberof FailResponse
     */
    'message'?: string;
}

