/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FetchUrlResultItem } from './fetch-url-result-item';

/**
 * 
 * @export
 * @interface FetchUrlResponse
 */
export interface FetchUrlResponse {
    /**
     * Results for each URL
     * @type {Array<FetchUrlResultItem>}
     * @memberof FetchUrlResponse
     */
    'results': Array<FetchUrlResultItem>;
    /**
     * Total number of URLs processed
     * @type {number}
     * @memberof FetchUrlResponse
     */
    'total': number;
    /**
     * Number of URLs successfully fetched
     * @type {number}
     * @memberof FetchUrlResponse
     */
    'succeeded': number;
    /**
     * Number of URLs that failed
     * @type {number}
     * @memberof FetchUrlResponse
     */
    'failed': number;
}

