/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response containing available graph labels
 * @export
 * @interface GraphLabelsResponse
 */
export interface GraphLabelsResponse {
    /**
     * List of available node labels in the knowledge graph
     * @type {Array<string>}
     * @memberof GraphLabelsResponse
     */
    'labels': Array<string>;
}

