/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Custom prompts for various index types
 * @export
 * @interface IndexPrompts
 */
export interface IndexPrompts {
    /**
     * Custom prompt for graph/entity extraction
     * @type {string}
     * @memberof IndexPrompts
     */
    'graph'?: string;
    /**
     * Custom prompt for document summarization
     * @type {string}
     * @memberof IndexPrompts
     */
    'summary'?: string;
    /**
     * Custom prompt for image analysis
     * @type {string}
     * @memberof IndexPrompts
     */
    'vision'?: string;
}

