/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Invitation } from './invitation';
// May contain unused imports in some cases
// @ts-ignore
import type { PageResult } from './page-result';

/**
 * A list of invitations
 * @export
 * @interface InvitationList
 */
export interface InvitationList {
    /**
     * 
     * @type {Array<Invitation>}
     * @memberof InvitationList
     */
    'items'?: Array<Invitation>;
    /**
     * 
     * @type {PageResult}
     * @memberof InvitationList
     */
    'pageResult'?: PageResult;
}

