/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InvitationCreate
 */
export interface InvitationCreate {
    /**
     * The username of the user
     * @type {string}
     * @memberof InvitationCreate
     */
    'username'?: string;
    /**
     * The email of the user
     * @type {string}
     * @memberof InvitationCreate
     */
    'email'?: string;
    /**
     * The role of the user (admin, rw, ro)
     * @type {string}
     * @memberof InvitationCreate
     */
    'role'?: InvitationCreateRoleEnum;
}

export const InvitationCreateRoleEnum = {
    admin: 'admin',
    rw: 'rw',
    ro: 'ro'
} as const;

export type InvitationCreateRoleEnum = typeof InvitationCreateRoleEnum[keyof typeof InvitationCreateRoleEnum];


