/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Invitation
 */
export interface Invitation {
    /**
     * The email of the user
     * @type {string}
     * @memberof Invitation
     */
    'email'?: string;
    /**
     * The token of the invitation
     * @type {string}
     * @memberof Invitation
     */
    'token'?: string;
    /**
     * The ID of the user who created the invitation
     * @type {string}
     * @memberof Invitation
     */
    'created_by'?: string;
    /**
     * The date and time the invitation was created
     * @type {string}
     * @memberof Invitation
     */
    'created_at'?: string;
    /**
     * Whether the invitation is valid
     * @type {boolean}
     * @memberof Invitation
     */
    'is_valid'?: boolean;
    /**
     * The date and time the invitation was used
     * @type {string}
     * @memberof Invitation
     */
    'used_at'?: string;
    /**
     * The role of the user (admin, rw, ro)
     * @type {string}
     * @memberof Invitation
     */
    'role'?: InvitationRoleEnum;
    /**
     * The date and time the invitation will expire
     * @type {string}
     * @memberof Invitation
     */
    'expires_at'?: string;
}

export const InvitationRoleEnum = {
    admin: 'admin',
    rw: 'rw',
    ro: 'ro'
} as const;

export type InvitationRoleEnum = typeof InvitationRoleEnum[keyof typeof InvitationRoleEnum];


