/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Configuration for knowledge graph generation
 * @export
 * @interface KnowledgeGraphConfig
 */
export interface KnowledgeGraphConfig {
    /**
     * List of entity types to extract during graph indexing
     * @type {Array<string>}
     * @memberof KnowledgeGraphConfig
     */
    'entity_types'?: Array<string>;
}

