/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LlmProviderModel } from './llm-provider-model';
// May contain unused imports in some cases
// @ts-ignore
import type { PageResult } from './page-result';

/**
 * 
 * @export
 * @interface LlmProviderModelList
 */
export interface LlmProviderModelList {
    /**
     * 
     * @type {Array<LlmProviderModel>}
     * @memberof LlmProviderModelList
     */
    'items'?: Array<LlmProviderModel>;
    /**
     * 
     * @type {PageResult}
     * @memberof LlmProviderModelList
     */
    'pageResult'?: PageResult;
}

