/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LlmProviderModelCreate
 */
export interface LlmProviderModelCreate {
    /**
     * Reference to LLMProvider.name
     * @type {string}
     * @memberof LlmProviderModelCreate
     */
    'provider_name': string;
    /**
     * API type for this model
     * @type {string}
     * @memberof LlmProviderModelCreate
     */
    'api': LlmProviderModelCreateApiEnum;
    /**
     * Model name/identifier
     * @type {string}
     * @memberof LlmProviderModelCreate
     */
    'model': string;
    /**
     * Custom LLM provider implementation
     * @type {string}
     * @memberof LlmProviderModelCreate
     */
    'custom_llm_provider': string;
    /**
     * Context window size (total tokens)
     * @type {number}
     * @memberof LlmProviderModelCreate
     */
    'context_window'?: number;
    /**
     * Maximum input tokens
     * @type {number}
     * @memberof LlmProviderModelCreate
     */
    'max_input_tokens'?: number;
    /**
     * Maximum output tokens
     * @type {number}
     * @memberof LlmProviderModelCreate
     */
    'max_output_tokens'?: number;
    /**
     * Tags for model categorization
     * @type {Array<string>}
     * @memberof LlmProviderModelCreate
     */
    'tags'?: Array<string>;
}

export const LlmProviderModelCreateApiEnum = {
    completion: 'completion',
    embedding: 'embedding',
    rerank: 'rerank'
} as const;

export type LlmProviderModelCreateApiEnum = typeof LlmProviderModelCreateApiEnum[keyof typeof LlmProviderModelCreateApiEnum];


