/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LlmProvider
 */
export interface LlmProvider {
    /**
     * Unique provider name identifier
     * @type {string}
     * @memberof LlmProvider
     */
    'name': string;
    /**
     * User ID of the provider owner, \"public\" for system providers
     * @type {string}
     * @memberof LlmProvider
     */
    'user_id': string;
    /**
     * Human-readable provider display name
     * @type {string}
     * @memberof LlmProvider
     */
    'label': string;
    /**
     * API dialect for completion/chat APIs
     * @type {string}
     * @memberof LlmProvider
     */
    'completion_dialect'?: string;
    /**
     * API dialect for embedding APIs
     * @type {string}
     * @memberof LlmProvider
     */
    'embedding_dialect'?: string;
    /**
     * API dialect for rerank APIs
     * @type {string}
     * @memberof LlmProvider
     */
    'rerank_dialect'?: string;
    /**
     * Whether custom base URLs are allowed
     * @type {boolean}
     * @memberof LlmProvider
     */
    'allow_custom_base_url'?: boolean;
    /**
     * Default API base URL for this provider
     * @type {string}
     * @memberof LlmProvider
     */
    'base_url': string;
    /**
     * Additional configuration data in JSON format
     * @type {string}
     * @memberof LlmProvider
     */
    'extra'?: string;
    /**
     * API key for this provider (if configured by user)
     * @type {string}
     * @memberof LlmProvider
     */
    'api_key'?: string;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof LlmProvider
     */
    'created'?: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof LlmProvider
     */
    'updated'?: string;
}

