/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LlmProviderModelUpdate
 */
export interface LlmProviderModelUpdate {
    /**
     * Custom LLM provider implementation
     * @type {string}
     * @memberof LlmProviderModelUpdate
     */
    'custom_llm_provider'?: string;
    /**
     * Context window size (total tokens)
     * @type {number}
     * @memberof LlmProviderModelUpdate
     */
    'context_window'?: number;
    /**
     * Maximum input tokens
     * @type {number}
     * @memberof LlmProviderModelUpdate
     */
    'max_input_tokens'?: number;
    /**
     * Maximum output tokens
     * @type {number}
     * @memberof LlmProviderModelUpdate
     */
    'max_output_tokens'?: number;
    /**
     * Tags for model categorization
     * @type {Array<string>}
     * @memberof LlmProviderModelUpdate
     */
    'tags'?: Array<string>;
}

