/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LlmProviderUpdateWithApiKey
 */
export interface LlmProviderUpdateWithApiKey {
    /**
     * Human-readable provider display name
     * @type {string}
     * @memberof LlmProviderUpdateWithApiKey
     */
    'label'?: string;
    /**
     * API dialect for completion/chat APIs
     * @type {string}
     * @memberof LlmProviderUpdateWithApiKey
     */
    'completion_dialect'?: string;
    /**
     * API dialect for embedding APIs
     * @type {string}
     * @memberof LlmProviderUpdateWithApiKey
     */
    'embedding_dialect'?: string;
    /**
     * API dialect for rerank APIs
     * @type {string}
     * @memberof LlmProviderUpdateWithApiKey
     */
    'rerank_dialect'?: string;
    /**
     * Whether custom base URLs are allowed
     * @type {boolean}
     * @memberof LlmProviderUpdateWithApiKey
     */
    'allow_custom_base_url'?: boolean;
    /**
     * Default API base URL for this provider
     * @type {string}
     * @memberof LlmProviderUpdateWithApiKey
     */
    'base_url'?: string;
    /**
     * Additional configuration data in JSON format
     * @type {string}
     * @memberof LlmProviderUpdateWithApiKey
     */
    'extra'?: string;
    /**
     * Optional API key for this provider
     * @type {string}
     * @memberof LlmProviderUpdateWithApiKey
     */
    'api_key'?: string;
    /**
     * Provider status - enable to create/update API key, disable to remove API key
     * @type {string}
     * @memberof LlmProviderUpdateWithApiKey
     */
    'status'?: LlmProviderUpdateWithApiKeyStatusEnum;
}

export const LlmProviderUpdateWithApiKeyStatusEnum = {
    enable: 'enable',
    disable: 'disable'
} as const;

export type LlmProviderUpdateWithApiKeyStatusEnum = typeof LlmProviderUpdateWithApiKeyStatusEnum[keyof typeof LlmProviderUpdateWithApiKeyStatusEnum];


