/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LLMConfig
 */
export interface LLMConfig {
    /**
     * 
     * @type {string}
     * @memberof LLMConfig
     */
    'model_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof LLMConfig
     */
    'model_service_provider'?: string;
    /**
     * 
     * @type {string}
     * @memberof LLMConfig
     */
    'custom_llm_provider'?: string;
}

