/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Login
 */
export interface Login {
    /**
     * The username of the user
     * @type {string}
     * @memberof Login
     */
    'username'?: string;
    /**
     * The password of the user
     * @type {string}
     * @memberof Login
     */
    'password'?: string;
}

