/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MarketplaceCollectionsCollectionIdGraphGet200Response
 */
export interface MarketplaceCollectionsCollectionIdGraphGet200Response {
    /**
     * 
     * @type {Array<object>}
     * @memberof MarketplaceCollectionsCollectionIdGraphGet200Response
     */
    'nodes'?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof MarketplaceCollectionsCollectionIdGraphGet200Response
     */
    'edges'?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof MarketplaceCollectionsCollectionIdGraphGet200Response
     */
    'collection_id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MarketplaceCollectionsCollectionIdGraphGet200Response
     */
    'read_only'?: boolean;
}

