/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MergeSuggestionTargetEntity } from './merge-suggestion-target-entity';

/**
 * Individual merge suggestion item
 * @export
 * @interface MergeSuggestionItem
 */
export interface MergeSuggestionItem {
    /**
     * Suggestion ID
     * @type {string}
     * @memberof MergeSuggestionItem
     */
    'id': string;
    /**
     * Collection ID
     * @type {string}
     * @memberof MergeSuggestionItem
     */
    'collection_id': string;
    /**
     * Suggestion batch ID
     * @type {string}
     * @memberof MergeSuggestionItem
     */
    'suggestion_batch_id': string;
    /**
     * Entity IDs suggested for merging
     * @type {Array<string>}
     * @memberof MergeSuggestionItem
     */
    'entity_ids': Array<string>;
    /**
     * LLM confidence score for this merge suggestion
     * @type {number}
     * @memberof MergeSuggestionItem
     */
    'confidence_score': number;
    /**
     * LLM-generated reason for suggesting this merge
     * @type {string}
     * @memberof MergeSuggestionItem
     */
    'merge_reason': string;
    /**
     * 
     * @type {MergeSuggestionTargetEntity}
     * @memberof MergeSuggestionItem
     */
    'suggested_target_entity': MergeSuggestionTargetEntity;
    /**
     * Status of the suggestion
     * @type {string}
     * @memberof MergeSuggestionItem
     */
    'status': MergeSuggestionItemStatusEnum;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof MergeSuggestionItem
     */
    'created': string;
    /**
     * User operation timestamp
     * @type {string}
     * @memberof MergeSuggestionItem
     */
    'operated_at'?: string;
}

export const MergeSuggestionItemStatusEnum = {
    PENDING: 'PENDING',
    ACCEPTED: 'ACCEPTED',
    REJECTED: 'REJECTED',
    EXPIRED: 'EXPIRED'
} as const;

export type MergeSuggestionItemStatusEnum = typeof MergeSuggestionItemStatusEnum[keyof typeof MergeSuggestionItemStatusEnum];


