/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request for generating node merge suggestions
 * @export
 * @interface MergeSuggestionsRequest
 */
export interface MergeSuggestionsRequest {
    /**
     * Maximum number of merge suggestions to return
     * @type {number}
     * @memberof MergeSuggestionsRequest
     */
    'max_suggestions'?: number;
    /**
     * Maximum number of concurrent LLM calls for batch analysis
     * @type {number}
     * @memberof MergeSuggestionsRequest
     */
    'max_concurrent_llm_calls'?: number;
    /**
     * Force regeneration of suggestions even if valid cached suggestions exist
     * @type {boolean}
     * @memberof MergeSuggestionsRequest
     */
    'force_refresh'?: boolean;
}

