/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelConfig } from './model-config';
// May contain unused imports in some cases
// @ts-ignore
import type { PageResult } from './page-result';

/**
 * 
 * @export
 * @interface ModelConfigList
 */
export interface ModelConfigList {
    /**
     * 
     * @type {Array<ModelConfig>}
     * @memberof ModelConfigList
     */
    'items'?: Array<ModelConfig>;
    /**
     * 
     * @type {PageResult}
     * @memberof ModelConfigList
     */
    'pageResult'?: PageResult;
}

