/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NodeData } from './node-data';
// May contain unused imports in some cases
// @ts-ignore
import type { NodeMeasured } from './node-measured';
// May contain unused imports in some cases
// @ts-ignore
import type { NodePosition } from './node-position';

/**
 * 
 * @export
 * @interface Node
 */
export interface Node {
    /**
     * Unique identifier for the node
     * @type {string}
     * @memberof Node
     */
    'id': string;
    /**
     * label for the node
     * @type {string}
     * @memberof Node
     */
    'ariaLabel'?: string;
    /**
     * Type of node
     * @type {string}
     * @memberof Node
     */
    'type': NodeTypeEnum;
    /**
     * Human-readable title of the node
     * @type {string}
     * @memberof Node
     */
    'title'?: string;
    /**
     * 
     * @type {NodeData}
     * @memberof Node
     */
    'data': NodeData;
    /**
     * 
     * @type {NodePosition}
     * @memberof Node
     */
    'position'?: NodePosition;
    /**
     * Drag handle of the node, only useful for frontend to drag the node
     * @type {string}
     * @memberof Node
     */
    'dragHandle'?: string;
    /**
     * 
     * @type {NodeMeasured}
     * @memberof Node
     */
    'measured'?: NodeMeasured;
    /**
     * Whether the node is selected, only useful for frontend to select the node
     * @type {boolean}
     * @memberof Node
     */
    'selected'?: boolean;
    /**
     * Whether the node is deletable, only useful for frontend to delete the node
     * @type {boolean}
     * @memberof Node
     */
    'deletable'?: boolean;
}

export const NodeTypeEnum = {
    start: 'start',
    vector_search: 'vector_search',
    fulltext_search: 'fulltext_search',
    graph_search: 'graph_search',
    merge: 'merge',
    rerank: 'rerank',
    llm: 'llm'
} as const;

export type NodeTypeEnum = typeof NodeTypeEnum[keyof typeof NodeTypeEnum];


