/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Measured position of the node, only useful for frontend to measure the node
 * @export
 * @interface NodeMeasured
 */
export interface NodeMeasured {
    /**
     * 
     * @type {number}
     * @memberof NodeMeasured
     */
    'width'?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeMeasured
     */
    'height'?: number;
}

