/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NodeDataInput } from './node-data-input';
// May contain unused imports in some cases
// @ts-ignore
import type { NodeDataOutput } from './node-data-output';

/**
 * 
 * @export
 * @interface NodeData
 */
export interface NodeData {
    /**
     * 
     * @type {NodeDataInput}
     * @memberof NodeData
     */
    'input': NodeDataInput;
    /**
     * 
     * @type {NodeDataOutput}
     * @memberof NodeData
     */
    'output': NodeDataOutput;
    /**
     * Whether the node is collapsed, only useful for frontend to collapse the node
     * @type {boolean}
     * @memberof NodeData
     */
    'collapsed'?: boolean;
}

