/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaginatedResponse
 */
export interface PaginatedResponse {
    /**
     * Total number of items
     * @type {number}
     * @memberof PaginatedResponse
     */
    'total'?: number;
    /**
     * Current page number
     * @type {number}
     * @memberof PaginatedResponse
     */
    'page'?: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof PaginatedResponse
     */
    'page_size'?: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof PaginatedResponse
     */
    'total_pages'?: number;
    /**
     * Whether there is a next page
     * @type {boolean}
     * @memberof PaginatedResponse
     */
    'has_next'?: boolean;
    /**
     * Whether there is a previous page
     * @type {boolean}
     * @memberof PaginatedResponse
     */
    'has_prev'?: boolean;
}

