/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PreviewRequest
 */
export interface PreviewRequest {
    /**
     * 
     * @type {string}
     * @memberof PreviewRequest
     */
    'template': string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PreviewRequest
     */
    'variables'?: { [key: string]: any; };
}

