/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Detailed prompt information with source and customization status
 * @export
 * @interface PromptDetail
 */
export interface PromptDetail {
    /**
     * Actual prompt content (resolved with priority)
     * @type {string}
     * @memberof PromptDetail
     */
    'content'?: string;
    /**
     * Source of the prompt
     * @type {string}
     * @memberof PromptDetail
     */
    'source'?: PromptDetailSourceEnum;
    /**
     * Whether user has customized this prompt
     * @type {boolean}
     * @memberof PromptDetail
     */
    'customized'?: boolean;
    /**
     * Optional description
     * @type {string}
     * @memberof PromptDetail
     */
    'description'?: string;
}

export const PromptDetailSourceEnum = {
    user: 'user',
    system: 'system',
    hardcoded: 'hardcoded'
} as const;

export type PromptDetailSourceEnum = typeof PromptDetailSourceEnum[keyof typeof PromptDetailSourceEnum];


