/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SystemPromptDetail } from './system-prompt-detail';
// May contain unused imports in some cases
// @ts-ignore
import type { SystemPromptsResponseValue } from './system-prompts-response-value';

/**
 * @type PromptsSystemGet200Response
 * @export
 */
export type PromptsSystemGet200Response = SystemPromptDetail | { [key: string]: SystemPromptsResponseValue; };


