/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Question type enumeration
 * @export
 * @enum {string}
 */

export const QuestionType = {
    FACTUAL: 'FACTUAL',
    INFERENTIAL: 'INFERENTIAL',
    USER_DEFINED: 'USER_DEFINED'
} as const;

export type QuestionType = typeof QuestionType[keyof typeof QuestionType];



