/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { QuestionsAddQuestionsInner } from './questions-add-questions-inner';

/**
 * 
 * @export
 * @interface QuestionsAdd
 */
export interface QuestionsAdd {
    /**
     * 
     * @type {Array<QuestionsAddQuestionsInner>}
     * @memberof QuestionsAdd
     */
    'questions': Array<QuestionsAddQuestionsInner>;
}

