/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LLMConfig } from './llmconfig';

/**
 * 
 * @export
 * @interface QuestionSetGenerate
 */
export interface QuestionSetGenerate {
    /**
     * 
     * @type {string}
     * @memberof QuestionSetGenerate
     */
    'collection_id': string;
    /**
     * 
     * @type {LLMConfig}
     * @memberof QuestionSetGenerate
     */
    'llm_config'?: LLMConfig;
    /**
     * 
     * @type {number}
     * @memberof QuestionSetGenerate
     */
    'question_count'?: number;
    /**
     * 
     * @type {string}
     * @memberof QuestionSetGenerate
     */
    'prompt'?: string;
}

