/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Question } from './question';

/**
 * 
 * @export
 * @interface QuestionSetDetail
 */
export interface QuestionSetDetail {
    /**
     * 
     * @type {string}
     * @memberof QuestionSetDetail
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof QuestionSetDetail
     */
    'user_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof QuestionSetDetail
     */
    'collection_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof QuestionSetDetail
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof QuestionSetDetail
     */
    'description'?: string;
    /**
     * 
     * @type {Array<Question>}
     * @memberof QuestionSetDetail
     */
    'questions'?: Array<Question>;
    /**
     * 
     * @type {string}
     * @memberof QuestionSetDetail
     */
    'gmt_created'?: string;
    /**
     * 
     * @type {string}
     * @memberof QuestionSetDetail
     */
    'gmt_updated'?: string;
}

