/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { QuestionSet } from './question-set';

/**
 * 
 * @export
 * @interface QuestionSetList
 */
export interface QuestionSetList {
    /**
     * 
     * @type {Array<QuestionSet>}
     * @memberof QuestionSetList
     */
    'items'?: Array<QuestionSet>;
    /**
     * 
     * @type {number}
     * @memberof QuestionSetList
     */
    'total'?: number;
    /**
     * 
     * @type {number}
     * @memberof QuestionSetList
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof QuestionSetList
     */
    'page_size'?: number;
}

