/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Question } from './question';

/**
 * 
 * @export
 * @interface QuestionSetCreate
 */
export interface QuestionSetCreate {
    /**
     * 
     * @type {string}
     * @memberof QuestionSetCreate
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof QuestionSetCreate
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof QuestionSetCreate
     */
    'collection_id'?: string;
    /**
     * A list of questions. Maximum 1000 questions are allowed.
     * @type {Array<Question>}
     * @memberof QuestionSetCreate
     */
    'questions'?: Array<Question>;
}

