/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface QuotasUserIdRecalculatePost200Response
 */
export interface QuotasUserIdRecalculatePost200Response {
    /**
     * 
     * @type {boolean}
     * @memberof QuotasUserIdRecalculatePost200Response
     */
    'success'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof QuotasUserIdRecalculatePost200Response
     */
    'message'?: string;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof QuotasUserIdRecalculatePost200Response
     */
    'updated_usage'?: { [key: string]: number; };
}

