/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface QuotaUpdateResponseUpdatedQuotasInner
 */
export interface QuotaUpdateResponseUpdatedQuotasInner {
    /**
     * Type of quota that was updated
     * @type {string}
     * @memberof QuotaUpdateResponseUpdatedQuotasInner
     */
    'quota_type': string;
    /**
     * Previous quota limit
     * @type {number}
     * @memberof QuotaUpdateResponseUpdatedQuotasInner
     */
    'old_limit': number;
    /**
     * New quota limit
     * @type {number}
     * @memberof QuotaUpdateResponseUpdatedQuotasInner
     */
    'new_limit': number;
}

