/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { QuotaInfo } from './quota-info';
// May contain unused imports in some cases
// @ts-ignore
import type { UserQuotaInfo } from './user-quota-info';
// May contain unused imports in some cases
// @ts-ignore
import type { UserQuotaList } from './user-quota-list';

/**
 * @type QuotasGet200Response
 * @export
 */
export type QuotasGet200Response = UserQuotaInfo | UserQuotaList;


