/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { QuotaUpdateResponseUpdatedQuotasInner } from './quota-update-response-updated-quotas-inner';

/**
 * Response after updating user quotas (supports both single and batch updates)
 * @export
 * @interface QuotaUpdateResponse
 */
export interface QuotaUpdateResponse {
    /**
     * Whether the update was successful
     * @type {boolean}
     * @memberof QuotaUpdateResponse
     */
    'success': boolean;
    /**
     * Status message
     * @type {string}
     * @memberof QuotaUpdateResponse
     */
    'message': string;
    /**
     * User ID that was updated
     * @type {string}
     * @memberof QuotaUpdateResponse
     */
    'user_id': string;
    /**
     * List of updated quotas
     * @type {Array<QuotaUpdateResponseUpdatedQuotasInner>}
     * @memberof QuotaUpdateResponse
     */
    'updated_quotas': Array<QuotaUpdateResponseUpdatedQuotasInner>;
}

