/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RebuildIndexesRequest
 */
export interface RebuildIndexesRequest {
    /**
     * Types of indexes to rebuild
     * @type {Array<string>}
     * @memberof RebuildIndexesRequest
     */
    'index_types': Array<RebuildIndexesRequestIndexTypesEnum>;
}

export const RebuildIndexesRequestIndexTypesEnum = {
    VECTOR: 'VECTOR',
    FULLTEXT: 'FULLTEXT',
    GRAPH: 'GRAPH',
    SUMMARY: 'SUMMARY',
    VISION: 'VISION'
} as const;

export type RebuildIndexesRequestIndexTypesEnum = typeof RebuildIndexesRequestIndexTypesEnum[keyof typeof RebuildIndexesRequestIndexTypesEnum];


