/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Reference
 */
export interface Reference {
    /**
     * 
     * @type {number}
     * @memberof Reference
     */
    'score'?: number;
    /**
     * 
     * @type {string}
     * @memberof Reference
     */
    'text'?: string;
    /**
     * 
     * @type {string}
     * @memberof Reference
     */
    'image_uri'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Reference
     */
    'metadata'?: { [key: string]: any; };
}

