/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RerankDocument } from './rerank-document';
// May contain unused imports in some cases
// @ts-ignore
import type { RerankUsage } from './rerank-usage';

/**
 * Response containing reranked documents in industry-standard format
 * @export
 * @interface RerankResponse
 */
export interface RerankResponse {
    /**
     * Object type identifier
     * @type {string}
     * @memberof RerankResponse
     */
    'object': string;
    /**
     * List of reranked documents ordered by relevance (highest first)
     * @type {Array<RerankDocument>}
     * @memberof RerankResponse
     */
    'data': Array<RerankDocument>;
    /**
     * Model used for reranking
     * @type {string}
     * @memberof RerankResponse
     */
    'model': string;
    /**
     * 
     * @type {RerankUsage}
     * @memberof RerankResponse
     */
    'usage': RerankUsage;
}

