/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Document content and metadata (only present if return_documents=true)
 * @export
 * @interface RerankDocumentDocument
 */
export interface RerankDocumentDocument {
    /**
     * Document text content
     * @type {string}
     * @memberof RerankDocumentDocument
     */
    'text': string;
    /**
     * Document metadata if provided in the request
     * @type {{ [key: string]: any; }}
     * @memberof RerankDocumentDocument
     */
    'metadata'?: { [key: string]: any; };
}

