/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RerankRequestDocuments } from './rerank-request-documents';

/**
 * Request to rerank documents based on query relevance
 * @export
 * @interface RerankRequest
 */
export interface RerankRequest {
    /**
     * LLM provider name (e.g., cohere, jina_ai)
     * @type {string}
     * @memberof RerankRequest
     */
    'provider': string;
    /**
     * Model name for reranking
     * @type {string}
     * @memberof RerankRequest
     */
    'model': string;
    /**
     * Search query to rank documents against
     * @type {string}
     * @memberof RerankRequest
     */
    'query': string;
    /**
     * 
     * @type {RerankRequestDocuments}
     * @memberof RerankRequest
     */
    'documents': RerankRequestDocuments;
    /**
     * Maximum number of top-ranked documents to return
     * @type {number}
     * @memberof RerankRequest
     */
    'top_k'?: number;
    /**
     * Whether to return document content in response
     * @type {boolean}
     * @memberof RerankRequest
     */
    'return_documents'?: boolean;
}

