/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RerankRequestDocumentsOneOfInner
 */
export interface RerankRequestDocumentsOneOfInner {
    /**
     * Document text content
     * @type {string}
     * @memberof RerankRequestDocumentsOneOfInner
     */
    'text': string;
    /**
     * Optional document metadata
     * @type {{ [key: string]: any; }}
     * @memberof RerankRequestDocumentsOneOfInner
     */
    'metadata'?: { [key: string]: any; };
}

