/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RerankDocumentDocument } from './rerank-document-document';

/**
 * Individual reranked document result
 * @export
 * @interface RerankDocument
 */
export interface RerankDocument {
    /**
     * Original index of the document in the input array
     * @type {number}
     * @memberof RerankDocument
     */
    'index': number;
    /**
     * Relevance score between 0 and 1 (higher is more relevant)
     * @type {number}
     * @memberof RerankDocument
     */
    'relevance_score': number;
    /**
     * 
     * @type {RerankDocumentDocument}
     * @memberof RerankDocument
     */
    'document'?: RerankDocumentDocument;
}

