/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Token usage information for the rerank request
 * @export
 * @interface RerankUsage
 */
export interface RerankUsage {
    /**
     * Total number of tokens processed (query + all documents)
     * @type {number}
     * @memberof RerankUsage
     */
    'total_tokens': number;
}

