/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * JSON Schema definition
 * @export
 * @interface SchemaDefinition
 */
export interface SchemaDefinition {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof SchemaDefinition
     */
    'type'?: SchemaDefinitionTypeEnum | null;
    /**
     * 
     * @type {object}
     * @memberof SchemaDefinition
     */
    'properties'?: object;
    /**
     * 
     * @type {Array<string>}
     * @memberof SchemaDefinition
     */
    'required'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof SchemaDefinition
     */
    'additionalProperties'?: boolean;
}

export const SchemaDefinitionTypeEnum = {
    object: 'object',
    array: 'array',
    string: 'string',
    number: 'number',
    integer: 'integer',
    boolean: 'boolean'
} as const;

export type SchemaDefinitionTypeEnum = typeof SchemaDefinitionTypeEnum[keyof typeof SchemaDefinitionTypeEnum];


