/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SettingsTestMineruTokenPost200Response
 */
export interface SettingsTestMineruTokenPost200Response {
    /**
     * 
     * @type {number}
     * @memberof SettingsTestMineruTokenPost200Response
     */
    'status_code'?: number;
    /**
     * 
     * @type {object}
     * @memberof SettingsTestMineruTokenPost200Response
     */
    'data'?: object;
}

