/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SharedCollection } from './shared-collection';

/**
 * Shared Collection list response
 * @export
 * @interface SharedCollectionList
 */
export interface SharedCollectionList {
    /**
     * List of shared Collections
     * @type {Array<SharedCollection>}
     * @memberof SharedCollectionList
     */
    'items': Array<SharedCollection>;
    /**
     * Total count (for pagination)
     * @type {number}
     * @memberof SharedCollectionList
     */
    'total': number;
    /**
     * Current page number
     * @type {number}
     * @memberof SharedCollectionList
     */
    'page': number;
    /**
     * Page size
     * @type {number}
     * @memberof SharedCollectionList
     */
    'page_size': number;
}

