/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Simple sharing status response
 * @export
 * @interface SharingStatusResponse
 */
export interface SharingStatusResponse {
    /**
     * Whether published to marketplace
     * @type {boolean}
     * @memberof SharingStatusResponse
     */
    'is_published': boolean;
    /**
     * Publication time, null when not published
     * @type {string}
     * @memberof SharingStatusResponse
     */
    'published_at'?: string;
}

