/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Configuration settings for shared collection features
 * @export
 * @interface SharedCollectionConfig
 */
export interface SharedCollectionConfig {
    /**
     * Whether vector search is enabled
     * @type {boolean}
     * @memberof SharedCollectionConfig
     */
    'enable_vector': boolean;
    /**
     * Whether fulltext search is enabled
     * @type {boolean}
     * @memberof SharedCollectionConfig
     */
    'enable_fulltext': boolean;
    /**
     * Whether knowledge graph is enabled
     * @type {boolean}
     * @memberof SharedCollectionConfig
     */
    'enable_knowledge_graph': boolean;
    /**
     * Whether summary generation is enabled
     * @type {boolean}
     * @memberof SharedCollectionConfig
     */
    'enable_summary': boolean;
    /**
     * Whether vision processing is enabled
     * @type {boolean}
     * @memberof SharedCollectionConfig
     */
    'enable_vision': boolean;
}

