/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UploadDocumentResponse } from './upload-document-response';

/**
 * 
 * @export
 * @interface StagedDocumentsResponse
 */
export interface StagedDocumentsResponse {
    /**
     * List of staged (UPLOADED) documents awaiting confirmation
     * @type {Array<UploadDocumentResponse>}
     * @memberof StagedDocumentsResponse
     */
    'documents': Array<UploadDocumentResponse>;
    /**
     * Total number of staged documents
     * @type {number}
     * @memberof StagedDocumentsResponse
     */
    'total': number;
}

