/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SystemPromptDetail
 */
export interface SystemPromptDetail {
    /**
     * 
     * @type {string}
     * @memberof SystemPromptDetail
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof SystemPromptDetail
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof SystemPromptDetail
     */
    'description'?: string;
}

