/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TagFilterCondition
 */
export interface TagFilterCondition {
    /**
     * Logical operation for tags in this condition
     * @type {string}
     * @memberof TagFilterCondition
     */
    'operation': TagFilterConditionOperationEnum;
    /**
     * List of tags for this condition
     * @type {Array<string>}
     * @memberof TagFilterCondition
     */
    'tags': Array<string>;
}

export const TagFilterConditionOperationEnum = {
    AND: 'AND',
    OR: 'OR'
} as const;

export type TagFilterConditionOperationEnum = typeof TagFilterConditionOperationEnum[keyof typeof TagFilterConditionOperationEnum];


