/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TagFilterCondition } from './tag-filter-condition';

/**
 * Tag filtering request. Empty request body or empty tag_filters returns recommend models by default.
 * @export
 * @interface TagFilterRequest
 */
export interface TagFilterRequest {
    /**
     * List of tag filter conditions (OR relationship between conditions). If not provided or empty, returns models with \"recommend\" tag by default.
     * @type {Array<TagFilterCondition>}
     * @memberof TagFilterRequest
     */
    'tag_filters'?: Array<TagFilterCondition>;
}

