/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Complete data of the target entity after merge
 * @export
 * @interface TargetEntityDataResponse
 */
export interface TargetEntityDataResponse {
    /**
     * The entity name that was kept (merge target)
     * @type {string}
     * @memberof TargetEntityDataResponse
     */
    'entity_name': string;
    /**
     * Entity type of the target entity
     * @type {string}
     * @memberof TargetEntityDataResponse
     */
    'entity_type': string;
    /**
     * Merged description of the target entity
     * @type {string}
     * @memberof TargetEntityDataResponse
     */
    'description': string;
    /**
     * Source ID information
     * @type {string}
     * @memberof TargetEntityDataResponse
     */
    'source_id'?: string;
    /**
     * File path information
     * @type {string}
     * @memberof TargetEntityDataResponse
     */
    'file_path'?: string;
}

