/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Optional target entity configuration. If not specified, auto-select entity with highest degree.
 * @export
 * @interface TargetEntityDataRequest
 */
export interface TargetEntityDataRequest {
    /**
     * Target entity name. If not specified, auto-select entity with highest degree
     * @type {string}
     * @memberof TargetEntityDataRequest
     */
    'entity_name'?: string;
    /**
     * Entity type for the target entity
     * @type {string}
     * @memberof TargetEntityDataRequest
     */
    'entity_type'?: string;
    /**
     * Description for the target entity
     * @type {string}
     * @memberof TargetEntityDataRequest
     */
    'description'?: string;
    /**
     * Source ID for the target entity
     * @type {string}
     * @memberof TargetEntityDataRequest
     */
    'source_id'?: string;
    /**
     * File path for the target entity
     * @type {string}
     * @memberof TargetEntityDataRequest
     */
    'file_path'?: string;
}

