/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TitleGenerateRequest
 */
export interface TitleGenerateRequest {
    /**
     * Maximum length of the generated title
     * @type {number}
     * @memberof TitleGenerateRequest
     */
    'max_length'?: number;
    /**
     * Language for the title generation (IETF BCP 47 tag)
     * @type {string}
     * @memberof TitleGenerateRequest
     */
    'language'?: TitleGenerateRequestLanguageEnum;
    /**
     * Number of most recent conversation turns to consider
     * @type {number}
     * @memberof TitleGenerateRequest
     */
    'turns'?: number;
}

export const TitleGenerateRequestLanguageEnum = {
    zh_CN: 'zh-CN',
    en_US: 'en-US',
    ja_JP: 'ja-JP',
    ko_KR: 'ko-KR'
} as const;

export type TitleGenerateRequestLanguageEnum = typeof TitleGenerateRequestLanguageEnum[keyof typeof TitleGenerateRequestLanguageEnum];


