/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateUserPromptsResponse
 */
export interface UpdateUserPromptsResponse {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserPromptsResponse
     */
    'message'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateUserPromptsResponse
     */
    'updated'?: Array<string>;
}

