/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Prompts to update (all fields are optional, only provided fields will be updated)
 * @export
 * @interface UpdateUserPromptsRequestPrompts
 */
export interface UpdateUserPromptsRequestPrompts {
    /**
     * Agent system prompt (persona definition)
     * @type {string}
     * @memberof UpdateUserPromptsRequestPrompts
     */
    'agent_system'?: string;
    /**
     * Agent query prompt template
     * @type {string}
     * @memberof UpdateUserPromptsRequestPrompts
     */
    'agent_query'?: string;
    /**
     * Graph index prompt for entity/relation extraction
     * @type {string}
     * @memberof UpdateUserPromptsRequestPrompts
     */
    'index_graph'?: string;
    /**
     * Summary index prompt for document summarization
     * @type {string}
     * @memberof UpdateUserPromptsRequestPrompts
     */
    'index_summary'?: string;
    /**
     * Vision index prompt for image content extraction
     * @type {string}
     * @memberof UpdateUserPromptsRequestPrompts
     */
    'index_vision'?: string;
}

