/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UploadDocumentResponse
 */
export interface UploadDocumentResponse {
    /**
     * ID of the uploaded document
     * @type {string}
     * @memberof UploadDocumentResponse
     */
    'document_id': string;
    /**
     * Name of the uploaded file
     * @type {string}
     * @memberof UploadDocumentResponse
     */
    'filename': string;
    /**
     * Size of the uploaded file in bytes
     * @type {number}
     * @memberof UploadDocumentResponse
     */
    'size': number;
    /**
     * Status of the document (UPLOADED for new uploads, or existing status for duplicate files)
     * @type {string}
     * @memberof UploadDocumentResponse
     */
    'status': UploadDocumentResponseStatusEnum;
}

export const UploadDocumentResponseStatusEnum = {
    UPLOADED: 'UPLOADED',
    PENDING: 'PENDING',
    RUNNING: 'RUNNING',
    COMPLETE: 'COMPLETE',
    FAILED: 'FAILED',
    DELETED: 'DELETED',
    EXPIRED: 'EXPIRED'
} as const;

export type UploadDocumentResponseStatusEnum = typeof UploadDocumentResponseStatusEnum[keyof typeof UploadDocumentResponseStatusEnum];


