/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PageResult } from './page-result';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 * A list of users
 * @export
 * @interface UserList
 */
export interface UserList {
    /**
     * 
     * @type {Array<User>}
     * @memberof UserList
     */
    'items'?: Array<User>;
    /**
     * 
     * @type {PageResult}
     * @memberof UserList
     */
    'pageResult'?: PageResult;
}

