/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserQuotaInfo } from './user-quota-info';

/**
 * List of user quota information (admin view)
 * @export
 * @interface UserQuotaList
 */
export interface UserQuotaList {
    /**
     * List of user quota information
     * @type {Array<UserQuotaInfo>}
     * @memberof UserQuotaList
     */
    'items': Array<UserQuotaInfo>;
}

