/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PromptDetail } from './prompt-detail';

/**
 * User\'s prompt configuration with all types
 * @export
 * @interface UserPromptsResponse
 */
export interface UserPromptsResponse {
    /**
     * 
     * @type {PromptDetail}
     * @memberof UserPromptsResponse
     */
    'agent_system'?: PromptDetail;
    /**
     * 
     * @type {PromptDetail}
     * @memberof UserPromptsResponse
     */
    'agent_query'?: PromptDetail;
    /**
     * 
     * @type {PromptDetail}
     * @memberof UserPromptsResponse
     */
    'index_graph'?: PromptDetail;
    /**
     * 
     * @type {PromptDetail}
     * @memberof UserPromptsResponse
     */
    'index_summary'?: PromptDetail;
    /**
     * 
     * @type {PromptDetail}
     * @memberof UserPromptsResponse
     */
    'index_vision'?: PromptDetail;
}

