/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ValidateRequest
 */
export interface ValidateRequest {
    /**
     * 
     * @type {string}
     * @memberof ValidateRequest
     */
    'type': ValidateRequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ValidateRequest
     */
    'template': string;
}

export const ValidateRequestTypeEnum = {
    agent_system: 'agent_system',
    agent_query: 'agent_query',
    index_graph: 'index_graph',
    index_summary: 'index_summary',
    index_vision: 'index_vision'
} as const;

export type ValidateRequestTypeEnum = typeof ValidateRequestTypeEnum[keyof typeof ValidateRequestTypeEnum];


