/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ValidateResponse
 */
export interface ValidateResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ValidateResponse
     */
    'valid'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ValidateResponse
     */
    'errors'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ValidateResponse
     */
    'warnings'?: Array<string>;
}

