/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VectorSearchParams
 */
export interface VectorSearchParams {
    /**
     * Top K results
     * @type {number}
     * @memberof VectorSearchParams
     */
    'topk'?: number;
    /**
     * Similarity threshold
     * @type {number}
     * @memberof VectorSearchParams
     */
    'similarity'?: number;
}

