/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WebReadResultItem } from './web-read-result-item';

/**
 * Web content reading response
 * @export
 * @interface WebReadResponse
 */
export interface WebReadResponse {
    /**
     * List of reading results
     * @type {Array<WebReadResultItem>}
     * @memberof WebReadResponse
     */
    'results': Array<WebReadResultItem>;
    /**
     * Total number of URLs processed
     * @type {number}
     * @memberof WebReadResponse
     */
    'total_urls': number;
    /**
     * Number of successful extractions
     * @type {number}
     * @memberof WebReadResponse
     */
    'successful': number;
    /**
     * Number of failed extractions
     * @type {number}
     * @memberof WebReadResponse
     */
    'failed': number;
    /**
     * Total processing time in seconds
     * @type {number}
     * @memberof WebReadResponse
     */
    'processing_time'?: number;
}

