/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Web content reading request
 * @export
 * @interface WebReadRequest
 */
export interface WebReadRequest {
    /**
     * List of URLs to read (for single URL, use array with one element)
     * @type {Array<string>}
     * @memberof WebReadRequest
     */
    'url_list': Array<string>;
    /**
     * Request timeout in seconds
     * @type {number}
     * @memberof WebReadRequest
     */
    'timeout'?: number;
    /**
     * Browser locale
     * @type {string}
     * @memberof WebReadRequest
     */
    'locale'?: string;
    /**
     * Maximum concurrent requests for multiple URLs
     * @type {number}
     * @memberof WebReadRequest
     */
    'max_concurrent'?: number;
}

