/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WebSearchResultItem } from './web-search-result-item';

/**
 * Web search response
 * @export
 * @interface WebSearchResponse
 */
export interface WebSearchResponse {
    /**
     * Original search query
     * @type {string}
     * @memberof WebSearchResponse
     */
    'query': string;
    /**
     * List of search results
     * @type {Array<WebSearchResultItem>}
     * @memberof WebSearchResponse
     */
    'results': Array<WebSearchResultItem>;
    /**
     * Total number of results found
     * @type {number}
     * @memberof WebSearchResponse
     */
    'total_results'?: number;
    /**
     * Search time in seconds
     * @type {number}
     * @memberof WebSearchResponse
     */
    'search_time'?: number;
}

