/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Workflow style
 * @export
 * @interface WorkflowStyle
 */
export interface WorkflowStyle {
    /**
     * 
     * @type {string}
     * @memberof WorkflowStyle
     */
    'edgeType'?: WorkflowStyleEdgeTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkflowStyle
     */
    'layoutDirection'?: WorkflowStyleLayoutDirectionEnum;
}

export const WorkflowStyleEdgeTypeEnum = {
    straight: 'straight',
    step: 'step',
    smoothstep: 'smoothstep',
    default: 'default',
    simplebezier: 'simplebezier'
} as const;

export type WorkflowStyleEdgeTypeEnum = typeof WorkflowStyleEdgeTypeEnum[keyof typeof WorkflowStyleEdgeTypeEnum];
export const WorkflowStyleLayoutDirectionEnum = {
    TB: 'TB',
    LR: 'LR'
} as const;

export type WorkflowStyleLayoutDirectionEnum = typeof WorkflowStyleLayoutDirectionEnum[keyof typeof WorkflowStyleLayoutDirectionEnum];


