/* tslint:disable */
/* eslint-disable */
/**
 * ATRAG API
 * ATRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Edge } from './edge';
// May contain unused imports in some cases
// @ts-ignore
import type { ExecutionConfig } from './execution-config';
// May contain unused imports in some cases
// @ts-ignore
import type { Node } from './node';
// May contain unused imports in some cases
// @ts-ignore
import type { SchemaDefinition } from './schema-definition';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowStyle } from './workflow-style';

/**
 * 
 * @export
 * @interface WorkflowDefinition
 */
export interface WorkflowDefinition {
    /**
     * Machine-readable identifier for the workflow
     * @type {string}
     * @memberof WorkflowDefinition
     */
    'name': string;
    /**
     * Human-readable title of the workflow
     * @type {string}
     * @memberof WorkflowDefinition
     */
    'title': string;
    /**
     * Detailed description of the workflow
     * @type {string}
     * @memberof WorkflowDefinition
     */
    'description'?: string;
    /**
     * Version number of the workflow definition
     * @type {string}
     * @memberof WorkflowDefinition
     */
    'version': string;
    /**
     * 
     * @type {ExecutionConfig}
     * @memberof WorkflowDefinition
     */
    'execution'?: ExecutionConfig;
    /**
     * Custom schema definitions used across the workflow
     * @type {{ [key: string]: SchemaDefinition; }}
     * @memberof WorkflowDefinition
     */
    'schema'?: { [key: string]: SchemaDefinition; };
    /**
     * List of nodes in the workflow
     * @type {Array<Node>}
     * @memberof WorkflowDefinition
     */
    'nodes': Array<Node>;
    /**
     * List of edges connecting nodes in the workflow
     * @type {Array<Edge>}
     * @memberof WorkflowDefinition
     */
    'edges': Array<Edge>;
    /**
     * 
     * @type {WorkflowStyle}
     * @memberof WorkflowDefinition
     */
    'style'?: WorkflowStyle;
}

